<?php
/**
 * @category    M2Commerce Enterprise
 * @package     M2Commerce_AddToCartPopup
 * @copyright   Copyright (c) 2023 M2Commerce Enterprise
 * @author      dawoodgondaldev@gmail.com
 */

/** @var \M2Commerce\AddToCartPopup\Block\Popup $block */
?>
<div data-placeholder="cartpopup" style="display: none;">
    <div data-bind="scope: 'cartpopup'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "cartpopup": {
                        "component": "M2Commerce_AddToCartPopup/js/cartpopup",
                        "shoppingCartUrl": "<?php echo $block->getShoppingCartUrl(); ?>",
                        "cartMessage": "<?php echo $block->getCartMessage(); ?>",
                        "successIcon" : "<?php echo $block->getSuccessIcon(); ?>"
                    }
                }
            }
        }
    }
</script>
